import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import SideBar from "@/components/sidebar";
import Footer from "@/components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Best Solana Meme Coin Sniper & Copy Trading Bot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <link rel="icon" href="/alogo.jpg" />
      <body
      suppressHydrationWarning={true} 
       
        className={`${geistSans.variable} gra ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <section className="w-full flex flex-col items-center justify-center pt-[200px] h-screen left-0">
          <div className="">
           {children}
           </div>
        <Footer />
        </section>
      </body>
    </html>
  );
}
