import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import SideBar from "@/components/sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
        className={`${geistSans.variable} gra ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <section className="w-full flex items-center justify-center h-screen left-0">
          <SideBar />
          <div className="">
           {children}
           </div>
        </section>
      </body>
    </html>
  );
}
