import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import SideBar from "@/components/sidebar";
import Footer from "@/components/footer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Best Solana Meme Coin Sniper & Copy Trading Bot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/alogo.jpg" />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable}  bg-gradient-to-r from-[#012109] via-black to-black antialiased min-h-screen items-center justify-center flex flex-col`}
      >
        <Navbar />
        <main className="flex-1 flex flex-col items-center justify-center w-[90%] px-4 sm:px-6 lg:px-8 pt-16 lg:pt-24">
          <div className="w-full max-w-7xl">
            {children}
          </div>
        </main>
        <Footer />
         {/* Tawk.to Script */}
      <Script
        id="tawk-to"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
              var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
              s1.async=true;
              s1.src='https://embed.tawk.to/68a6c1a425183f1924968a58/1j35m8s1k';
              s1.charset='UTF-8';
              s1.setAttribute('crossorigin','*');
              s0.parentNode.insertBefore(s1,s0);
            })();
          `,
        }}
      />
      </body>
    </html>
  );
}